# Generated by Django 5.0.6 on 2024-07-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profile_picture',
        ),
    ]
