# Generated by Django 5.0.6 on 2024-08-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_account_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
