# Generated by Django 5.0.6 on 2024-08-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='wallet_balance',
        ),
    ]
