# Generated by Django 5.0.6 on 2024-08-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_account_referral_code_account_referred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='account',
            name='referred_by',
        ),
    ]
