# Generated by Django 5.0.6 on 2024-07-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
