# Generated by Django 5.0.6 on 2024-08-02 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_wishlistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
