# Generated by Django 5.0.6 on 2024-07-09 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_brand_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='brand',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
