# Generated by Django 5.0.6 on 2024-07-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_qty_per_person',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
