# Generated by Django 5.0.6 on 2024-07-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_order_order_number_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=1, max_length=50, unique=True),
        ),
    ]
