# Generated by Django 5.0.6 on 2024-07-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='f58db28ab63f466b9c7e10a8971a2c48', max_length=50, unique=True),
        ),
    ]
