# Generated by Django 5.0.6 on 2024-07-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_cartitem_color_cartitem_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='36020b73edb74c96976d8a1dfe08309a', max_length=50, unique=True),
        ),
    ]
