# Generated by Django 5.0.6 on 2024-07-23 04:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_remove_order_items_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='eea0b750cff342c18848a35a73d5a087', max_length=50, unique=True),
        ),
    ]
