# Generated by Django 5.0.6 on 2024-07-23 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_order_estimated_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='estimated_delivery_date',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_days',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='7af4088e4d0849cfb259d0bc34714b41', max_length=50, unique=True),
        ),
    ]
