# Generated by Django 5.0.6 on 2024-07-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_alter_order_order_date_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time_days',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='1e768629e5d04c84873c51a6a3f79066', max_length=50, unique=True),
        ),
    ]
