# Generated by Django 5.0.6 on 2024-07-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_remove_order_delivery_time_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='2fed7e910880453eb92488e7bab865e5', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(related_name='brands', to='products.category'),
        ),
    ]
