# Generated by Django 5.0.6 on 2024-08-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_alter_order_order_number_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='9e1a05c4cbcf4460b27c253b2665fbad', max_length=50, unique=True),
        ),
    ]
