# Generated by Django 5.0.6 on 2024-08-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_order_updated_at_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='6658fafb9fa14ec695ae318d0d53c3eb', max_length=50, unique=True),
        ),
    ]
