# Generated by Django 5.0.6 on 2024-08-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='1c245dc012244d39b5c56e8aa83bd40b', max_length=50, unique=True),
        ),
    ]
