# Generated by Django 5.0.6 on 2024-08-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='bf325369a83c41a5839e3a81a36146f7', max_length=50, unique=True),
        ),
    ]
