# Generated by Django 5.0.6 on 2024-08-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='40921d9f775a440e91b0394e83774017', max_length=50, unique=True),
        ),
    ]
