# Generated by Django 5.0.6 on 2024-08-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='40ba2f5e7ff24fecb46592f3021273c6', max_length=50, unique=True),
        ),
    ]
