# Generated by Django 5.0.6 on 2024-08-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='bceae1503ed54b07b173c6e0348d43e5', max_length=50, unique=True),
        ),
    ]
