# Generated by Django 5.0.6 on 2024-08-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='c4b747c0f8274cc6af8a1a2965dee663', max_length=50, unique=True),
        ),
    ]
