# Generated by Django 5.0.6 on 2024-08-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='af114039247e49bb815691651c81c887', max_length=50, unique=True),
        ),
    ]
