# Generated by Django 5.0.6 on 2024-08-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='becb497d88a64f83a0b07d7952379cd5', max_length=50, unique=True),
        ),
    ]
