# Generated by Django 5.0.6 on 2024-08-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='6a56045e8faa493683323332b09c24cb', max_length=50, unique=True),
        ),
    ]
