# Generated by Django 5.0.6 on 2024-08-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='a6f2fbf1c0da4aa684b787e502b69ebb', max_length=50, unique=True),
        ),
    ]
