# Generated by Django 5.0.6 on 2024-08-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_coupon_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='a8f31fa896a348e9b50ba7a17b8f6942', max_length=50, unique=True),
        ),
    ]
