# Generated by Django 5.0.6 on 2024-08-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0062_alter_order_order_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='0c6df8f467724633a6719fb6972f18a2', max_length=50, unique=True),
        ),
    ]
