# Generated by Django 5.0.6 on 2024-08-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_delete_coupon_alter_order_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='inactive', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='b79d30b21d59437dbb78127c31f7807a', max_length=50, unique=True),
        ),
    ]
