# Generated by Django 5.0.6 on 2024-08-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0064_coupon_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='76eca86b786644df99257bb820d51924', max_length=50, unique=True),
        ),
    ]
