# Generated by Django 5.0.6 on 2024-08-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0073_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='d99859a0b31549d5a82952901d9b0267', max_length=50, unique=True),
        ),
    ]
