# Generated by Django 5.0.6 on 2024-08-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0074_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='0bd72e4c36384099ae2b1086ec6c26a3', max_length=50, unique=True),
        ),
    ]
