# Generated by Django 5.0.6 on 2024-08-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0077_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='73ff2b180cbc46d498b4daa04e42081d', max_length=50, unique=True),
        ),
    ]
