# Generated by Django 5.0.6 on 2024-08-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0078_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='76d8eb82b13f4166aed771826431eaf7', max_length=50, unique=True),
        ),
    ]
