# Generated by Django 5.0.6 on 2024-08-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0079_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_by_razorpay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='7fa1bedb1703463a804422e1a3fc24fb', max_length=50, unique=True),
        ),
    ]
