# Generated by Django 5.0.6 on 2024-08-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0080_order_paid_by_razorpay_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid_by_razorpay',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='94f3d919f1744ce599251bfdd154dbd7', max_length=50, unique=True),
        ),
    ]
