# Generated by Django 5.0.6 on 2024-08-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0082_remove_order_grand_total_order_coupon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='7045b6e0f10e4ef28ed53c8e32925e10', max_length=50, unique=True),
        ),
    ]
