# Generated by Django 5.0.6 on 2024-08-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0084_order_grand_total_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='4a7a416840f8409090d1c83e45fdfd2f', max_length=50, unique=True),
        ),
    ]
