# Generated by Django 5.0.6 on 2024-08-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0085_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='6246131f5d9b47439371d549483c77a4', max_length=50, unique=True),
        ),
    ]
