# Generated by Django 5.0.6 on 2024-08-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0088_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='fe46bc741c2c479b9e91231ee9027c4d', max_length=50, unique=True),
        ),
    ]
