# Generated by Django 5.0.6 on 2024-08-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0089_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='2b3f0adbc18f4efe874bd48fc2c3e01c', max_length=50, unique=True),
        ),
    ]
