# Generated by Django 5.0.6 on 2024-08-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0090_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='abe1e4d6cf5049ffbfff7fe25cf0bc93', max_length=50, unique=True),
        ),
    ]
