# Generated by Django 5.0.6 on 2024-08-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0095_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='9d273ccd774c450ea77f3479696af624', max_length=50, unique=True),
        ),
    ]
