# Generated by Django 5.0.6 on 2024-08-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0097_alter_order_order_number_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='0def78350ce0441bbbd35cb7ea88f78b', max_length=50, unique=True),
        ),
    ]
