# Generated by Django 5.0.6 on 2024-08-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0099_cartitem_color_cartitem_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='ffcb79f4442e4bcc86a70fc5760b2dfc', max_length=50, unique=True),
        ),
    ]
