# Generated by Django 5.0.6 on 2024-08-05 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0101_cartitem_product_variant_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='80d644b11c554acfa9de5e5f5ce800a0', max_length=50, unique=True),
        ),
    ]
