# Generated by Django 5.0.6 on 2024-08-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0103_alter_cartitem_product_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='4a57396a1b5e4f17917db3e9f4619218', max_length=50, unique=True),
        ),
    ]
