# Generated by Django 5.0.6 on 2024-08-05 18:12

from django.db import migrations

def populate_product_variant(apps, schema_editor):
    CartItem = apps.get_model('products', 'CartItem')
    Product = apps.get_model('products', 'Product')
    ProductVariant = apps.get_model('products', 'ProductVariant')
    
    for item in CartItem.objects.all():
        # Example logic: assume `Product` has a default variant
        # Modify this logic to suit your needs
        variant = ProductVariant.objects.filter(product=item.product).first()
        if variant:
            item.product_variant = variant
            item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0104_alter_order_order_number'),
    ]

    operations = [
        migrations.RunPython(populate_product_variant),
    ]