# Generated by Django 5.0.6 on 2024-08-05 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0105_auto_20240805_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productvariant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='9289349f5a1649c8b3ab253e49057ebd', max_length=50, unique=True),
        ),
    ]
