# Generated by Django 5.0.6 on 2024-08-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0106_alter_cartitem_product_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_variant',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='de1bc19066534a9eae58b6ae16d6f54b', max_length=50, unique=True),
        ),
    ]
