# Generated by Django 5.0.6 on 2024-08-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0108_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='9db0174c35484f69a737547186069290', max_length=50, unique=True),
        ),
    ]
