# Generated by Django 5.0.6 on 2024-08-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0110_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='439f304ab31b4d52a098dea908ba9c7d', max_length=50, unique=True),
        ),
    ]
