# Generated by Django 5.0.6 on 2024-08-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0111_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='65ac31083f7d4fc0a5c66f0147246299', max_length=50, unique=True),
        ),
    ]
