# Generated by Django 5.0.6 on 2024-08-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0112_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='922165e43501413ca53f14ad29398bf6', max_length=50, unique=True),
        ),
    ]
