# Generated by Django 5.0.6 on 2024-08-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0113_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='ffd34e3fdd7a46cf896d742194c8f35d', max_length=50, unique=True),
        ),
    ]
