# Generated by Django 5.0.6 on 2024-08-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0116_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='bb141d34012b4057b5c693938a651cc6', max_length=50, unique=True),
        ),
    ]
