# Generated by Django 5.0.6 on 2024-08-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0119_alter_order_order_number_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='ed48e42d75ea486bb7e44c0984266fd0', max_length=50, unique=True),
        ),
    ]
