# Generated by Django 5.0.6 on 2024-08-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0124_alter_order_order_number_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='bb58027ab7114fe1a7e566d279d7fbdc', max_length=50, unique=True),
        ),
    ]
