# Generated by Django 5.0.6 on 2024-08-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0126_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='690306e0129140ad879b6da3022152db', max_length=50, unique=True),
        ),
    ]
