# Generated by Django 5.0.6 on 2024-08-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0128_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='23db5c9374814c8ba99aab38555385f4', max_length=50, unique=True),
        ),
    ]
