# Generated by Django 5.0.6 on 2024-08-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0129_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='f5329af4aa01406db1df1e3971e9c858', max_length=50, unique=True),
        ),
    ]
