# Generated by Django 5.0.6 on 2024-08-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0130_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='921eea4dcb5c40f9999c5c612826a4c3', max_length=50, unique=True),
        ),
    ]
