# Generated by Django 5.0.6 on 2024-08-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0131_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='f9c1ff2d150d42de8ec0c4ff387a7148', max_length=50, unique=True),
        ),
    ]
