# Generated by Django 5.0.6 on 2024-08-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0135_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='offer',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='6014a2ae9e1b491589b32fdb99a78f97', max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
