# Generated by Django 5.0.6 on 2024-08-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0136_remove_brand_offer_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='offer_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='category',
            name='offer_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='85aa577ce34a418aabe8a5659bce4c9a', max_length=50, unique=True),
        ),
    ]
