# Generated by Django 5.0.6 on 2024-08-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0138_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='3bebbf569c1e452a9a2e8eb28dd494fc', max_length=50, unique=True),
        ),
    ]
