# Generated by Django 5.0.6 on 2024-08-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0139_product_discount_percentage_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='offer_percentage',
        ),
        migrations.RemoveField(
            model_name='category',
            name='offer_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='18165f9b53084c2aa82debf4b913db58', max_length=50, unique=True),
        ),
    ]
