# Generated by Django 5.0.6 on 2024-08-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0140_remove_brand_offer_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage, e.g., 10.00 for 10% off', max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='9f1e3698f902458dae766f2e45061fc5', max_length=50, unique=True),
        ),
    ]
