# Generated by Django 5.0.6 on 2024-08-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0141_product_discount_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Offer percentage for the category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='8cad4c20bf384b1e99e52459a5cf6fa3', max_length=50, unique=True),
        ),
    ]
