# Generated by Django 5.0.6 on 2024-08-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0142_category_offer_percentage_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage, e.g., 10.00 for 10% off', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='947701859a614fa4b47f195536e9e06a', max_length=50, unique=True),
        ),
    ]
