# Generated by Django 5.0.6 on 2024-08-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0144_remove_category_offer_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage applied to the product', max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='349e57070c6b475ab43b81c9c4b3768e', max_length=50, unique=True),
        ),
    ]
