# Generated by Django 5.0.6 on 2024-08-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0145_product_discount_percentage_alter_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_percentage',
            new_name='product_offer',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_offer',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage applied to all products under this brand', max_digits=5),
        ),
        migrations.AddField(
            model_name='category',
            name='category_offer',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage applied to all products under this category', max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='a40ffb3281d3424589698fe19709c111', max_length=50, unique=True),
        ),
    ]
