# Generated by Django 5.0.6 on 2024-08-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0146_rename_discount_percentage_product_product_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='81eb19c37a864ee993738bf5b18e3b4b', max_length=50, unique=True),
        ),
    ]
