# Generated by Django 5.0.6 on 2024-08-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0147_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='9b7920b3b6104172ac27a980d50fcdf3', max_length=50, unique=True),
        ),
    ]
