# Generated by Django 5.0.6 on 2024-08-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0149_order_coupon_code_order_coupon_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon_discount',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='f2a6905525b34ca8b868a2ec82aa3b31', max_length=50, unique=True),
        ),
    ]
