# Generated by Django 5.0.6 on 2024-08-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0151_order_coupon_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='e22bd589dcbd444e92652d9567596da9', max_length=50, unique=True),
        ),
    ]
