# Generated by Django 5.0.6 on 2024-08-11 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0153_order_applied_coupon_order_coupon_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='applied_coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon_discount',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='346de030ca314bac8d7c662f960351cc', max_length=50, unique=True),
        ),
    ]
