# Generated by Django 5.0.6 on 2024-08-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0154_remove_order_applied_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='5c3ede7167e0491a99a8b603229e6b71', max_length=50, unique=True),
        ),
    ]
