# Generated by Django 5.0.6 on 2024-08-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0157_order_coupon_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='42e5926980b2447788b616a168b72c6f', max_length=50, unique=True),
        ),
    ]
