# Generated by Django 5.0.6 on 2024-08-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0159_order_applied_coupon_code_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='applied_coupon_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='referral_discount_amount',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='f80e9cc2a2c342869d539b9185fa9bfa', max_length=50, unique=True),
        ),
    ]
