# Generated by Django 5.0.6 on 2024-08-12 17:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0160_remove_order_applied_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_coupon_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='6952774a0414441991a39f7c87ec57d2', max_length=50, unique=True),
        ),
    ]
