# Generated by Django 5.0.6 on 2024-08-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0162_remove_order_applied_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='99fea5e787b2402990aba7408da9dcfa', max_length=50, unique=True),
        ),
    ]
