# Generated by Django 5.0.6 on 2024-08-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0166_remove_orderitem_total_price_order_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='04160f8efb0848f0b04ed6b8b3a88693', max_length=50, unique=True),
        ),
    ]
