# Generated by Django 5.0.6 on 2024-08-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0167_remove_order_payment_status_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='4e6a3a5bf4ee41ad962402b7b04df410', max_length=50, unique=True),
        ),
    ]
