# Generated by Django 5.0.6 on 2024-08-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0171_alter_order_order_number_alter_orderitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='459c96ec9cf04004ac9e3bd639c51724', max_length=50, unique=True),
        ),
    ]
