# Generated by Django 5.0.6 on 2024-08-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0173_remove_order_payment_status_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='f6cb5d29d98d492a8e75438b4c18a8a2', max_length=50, unique=True),
        ),
    ]
