# Generated by Django 5.0.6 on 2024-08-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0175_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='149b1fe506eb450b99a08a57cc0ef8fb', max_length=50, unique=True),
        ),
    ]
