# Generated by Django 5.0.6 on 2024-08-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0177_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='e7e3bd34cfcc40d1a1e987d668250ba8', max_length=50, unique=True),
        ),
    ]
