# Generated by Django 5.0.6 on 2024-08-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0178_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='dadb220ec14043118eb58699b235c493', max_length=50, unique=True),
        ),
    ]
