# Generated by Django 5.0.6 on 2024-08-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0181_orderitem_size_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='685cd420b59f4ff2a174e66df3a5d8d1', max_length=50, unique=True),
        ),
    ]
