# Generated by Django 5.0.6 on 2024-08-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0183_alter_order_order_number_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='f926789a9a20441d895d9e83e2d6d44f', max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
