# Generated by Django 5.0.6 on 2024-08-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0186_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='b310ab19d0f640c281ce95d04dda8bb0', max_length=50, unique=True),
        ),
    ]
