# Generated by Django 5.0.6 on 2024-08-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0188_alter_order_order_number_orderaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='6a9a19d3a4f74332933a912d51c4ee01', max_length=50, unique=True),
        ),
    ]
