# Generated by Django 5.0.6 on 2024-08-25 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_delete_wishlistitem'),
        ('products', '0189_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='7ef13beef9ff4e918f7041cc4301915e', max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='OrderAddress',
        ),
    ]
