# Generated by Django 5.0.6 on 2024-08-25 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_orderaddress'),
        ('products', '0190_alter_order_address_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='User.orderaddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='e4b03197f40b4e86a0806fd9024bcbab', max_length=50, unique=True),
        ),
    ]
