# Generated by Django 5.0.6 on 2024-08-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0191_remove_order_payment_method_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='dffa2742d70e47eb9735589bde4a6475', max_length=50, unique=True),
        ),
    ]
