# Generated by Django 5.0.6 on 2024-08-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0192_order_payment_method_alter_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='price',
            new_name='original_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='7228ff5322954d1b903a00170c647b5e', max_length=50, unique=True),
        ),
    ]
