# Generated by Django 5.0.6 on 2024-08-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0193_rename_price_productvariant_original_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='6a9a4ef1835e411ca16fd4e480d25516', max_length=50, unique=True),
        ),
    ]
