# Generated by Django 5.0.6 on 2024-08-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0194_productvariant_offer_price_alter_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='original_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='offer_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='d70a9d050f8e4ce397623b1f85ccbb9b', max_length=50, unique=True),
        ),
    ]
