# Generated by Django 5.0.6 on 2024-08-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0195_rename_original_price_productvariant_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='68de657168214173ab9a26e06190633e', max_length=50, unique=True),
        ),
    ]
