# Generated by Django 5.0.6 on 2024-09-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0197_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='f17613f723b14c6199cc23648f1cec36', max_length=50, unique=True),
        ),
    ]
