# Generated by Django 5.0.6 on 2024-09-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0198_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='cc09c95ee6954d398d06db5a74f46c0a', max_length=50, unique=True),
        ),
    ]
