# Generated by Django 5.0.6 on 2024-09-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0199_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='fa429d96e8db4168a9d18083942c97e1', max_length=50, unique=True),
        ),
    ]
