# Generated by Django 5.0.6 on 2024-08-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_returnrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='user',
        ),
    ]
