# Generated by Django 5.0.6 on 2024-08-10 07:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_referral_referred_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5),
        ),
    ]
