# Generated by Django 5.0.6 on 2024-08-10 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_referral_referral_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='used_referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
