# Generated by Django 5.0.6 on 2024-08-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_referral_used_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='used_by',
        ),
    ]
